version: "3.8"

services:
  php-fpm:
    build: .
    container_name: myportfolio-php
    env_file:
      - .env
    volumes:
      - ..:/var/www/html
      - /var/log/apps/myportfolio:/var/www/html/logs
    networks:
      - myportfolio-network

  nginx:
    image: nginx:alpine
    container_name: myportfolio-nginx
    ports:
      - "82:80"
    volumes:
      - ..:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/log/apps/myportfolio/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - myportfolio-network

# volumes:
#   logs:

networks:
  myportfolio-network:
    driver: bridge
